// Generated by scripts/generate-plugins.ts. Do not edit.
import type { ChartId, ChartModule } from "@cie/schema";
import p0 from "./r1.chart.ts";
import p1 from "./s1.chart.ts";
import p2 from "./s2.chart.ts";
import p3 from "./s3.chart.ts";
import p4 from "./s4.chart.ts";
import p5 from "./s5.chart.ts";
import p6 from "./s6.chart.ts";
import p7 from "./s7.chart.ts";
import p8 from "./s8.chart.ts";
import p9 from "./s9.chart.ts";
import p10 from "./s10.chart.ts";
import p11 from "./s11.chart.ts";
import p12 from "./s12.chart.ts";
import p13 from "./s13.chart.ts";
import p14 from "./s14.chart.ts";
import p15 from "./s15.chart.ts";
import p16 from "./s16.chart.ts";
import p17 from "./s17.chart.ts";
import p18 from "./s18.chart.ts";
import p19 from "./s19.chart.ts";
import p20 from "./s20.chart.ts";
import p21 from "./s21.chart.ts";
import p22 from "./s22.chart.ts";
import p23 from "./s23.chart.ts";
import p24 from "./s24.chart.ts";
import p25 from "./s25.chart.ts";
import p26 from "./s26.chart.ts";
import p27 from "./s27.chart.ts";
import p28 from "./s28.chart.ts";
import p29 from "./s29.chart.ts";
import p30 from "./generic.chart.ts";
export const CHART_MODULES = {
  "R1": p0,
  "S1": p1,
  "S2": p2,
  "S3": p3,
  "S4": p4,
  "S5": p5,
  "S6": p6,
  "S7": p7,
  "S8": p8,
  "S9": p9,
  "S10": p10,
  "S11": p11,
  "S12": p12,
  "S13": p13,
  "S14": p14,
  "S15": p15,
  "S16": p16,
  "S17": p17,
  "S18": p18,
  "S19": p19,
  "S20": p20,
  "S21": p21,
  "S22": p22,
  "S23": p23,
  "S24": p24,
  "S25": p25,
  "S26": p26,
  "S27": p27,
  "S28": p28,
  "S29": p29,
  "generic": p30,
} satisfies { [K in ChartId]: ChartModule<K> };
