// Generated by scripts/generate-plugins.ts. Do not edit.
import type { ChartId, ChartDescriptor } from "../index.ts";
export const CHART_DESCRIPTORS = {
  "R1": {
    "id": "R1",
    "name": "Replay timeline (twin run)",
    "form": "RaceWindow",
    "version": 1,
    "compiler": "specialized",
    "offline": "derived",
    "aliases": [
      "replay timeline",
      "twin replay",
      "race timeline",
      "timeout replay",
      "what-if simulation",
      "scenario replay"
    ],
    "requiredKinds": [],
    "requiredAcrossRepository": [],
    "concern": "Reliability",
    "renderer": "race-timeline",
    "questionAnswered": "What actually happens to requests under this load or fault scenario, on the pinned twin model?",
    "description": "Runs the pinned reference twin model deterministically for the requested scenario (baseline, timeout, saturation, retry storm) and draws the sampled request lifecycles across stations: service blocks, queued waits, retries, timeouts and drops, with run metrics and a MODEL_PREDICTION result class. This is a bounded model prediction in simulated time — not observed production timing, and not a capacity certificate; a calibrated baseline or an isolated-exec experiment upgrades the result class.",
    "example": "Replay checkout at 80 requests per second with a 14 ms ledger timeout and show which requests exhaust their retries.",
    "needs": []
  },
  "S1": {
    "id": "S1",
    "name": "Container / component architecture",
    "form": "GeneratedChart",
    "version": 3,
    "compiler": "standard",
    "offline": "derived",
    "aliases": [
      "C4 container / component architecture",
      "C4 container component architecture",
      "C4 component diagram",
      "container diagram",
      "architecture diagram"
    ],
    "requiredKinds": [],
    "requiredAcrossRepository": [],
    "concern": "Structure",
    "renderer": "view-spec",
    "questionAnswered": "How are the main components connected?",
    "description": "Show the main components and who calls what, rendered as an evidence-grounded component graph. Architecture boundaries (Redis, MySQL and other stores) appear only where the indexed code names them; unsupported boundaries are listed as gaps instead of drawn. Also covers UML component, deployment and hexagonal port-and-adapter layouts.",
    "example": "Build a container architecture diagram for the reserve fast path. Show who calls what and distinguish Redis from MySQL using repository evidence.",
    "needs": []
  },
  "S2": {
    "id": "S2",
    "name": "Activity flow / swimlane",
    "form": "TransactionJourney",
    "version": 4,
    "compiler": "standard",
    "offline": "derived",
    "aliases": [
      "Reserve fast-path sequence / swimlane",
      "reserve fast path sequence swimlane",
      "reserve sequence",
      "swimlane diagram",
      "activity diagram",
      "activity flow"
    ],
    "requiredKinds": [],
    "requiredAcrossRepository": [],
    "concern": "Behavior",
    "renderer": "activity",
    "questionAnswered": "How does this operation flow across components?",
    "description": "Follow reserve through its callers and callees as a swimlane journey: lanes per module, conditional branches, transaction markers and failure exits, ordered by static control-flow (not observed runtime timing). This is a swimlane journey rather than a full UML sequence diagram; for lifelines, ordered messages and alt/opt/loop fragments use the UML sequence diagram (S28). Also serves as a UML activity diagram or control-flow graph for any single operation.",
    "example": "Draw the reserve activity flow across Redis and MySQL lanes. Identify decision points and source-backed links; distinguish interpreted branch labels from indexed relationships.",
    "needs": []
  },
  "S3": {
    "id": "S3",
    "name": "BatchId lifecycle state machine",
    "form": "GeneratedChart",
    "version": 4,
    "compiler": "specialized",
    "offline": "gap",
    "aliases": [
      "BatchId lifecycle state machine",
      "state machine",
      "state diagram",
      "lifecycle diagram"
    ],
    "requiredKinds": [],
    "requiredAcrossRepository": [],
    "concern": "State and rules",
    "renderer": "state",
    "questionAnswered": "What states and transitions are supported?",
    "description": "Map reserve, post, rollback and idempotent repeats from observed code paths; missing transitions are called out as gaps. Cardinality, timing and token semantics require separate views; this view preserves states, guards, forbidden paths and replay interpretations.",
    "example": "Draw the batchId lifecycle as a state machine: reserve → post or rollback, including idempotent repeats. Use only states and transitions evidenced in the code, and list gaps.",
    "needs": []
  },
  "S4": {
    "id": "S4",
    "name": "Ledger and entry relationships",
    "form": "GeneratedChart",
    "version": 4,
    "compiler": "specialized",
    "offline": "gap",
    "aliases": [
      "Ledger and entry relationships",
      "ledger and entry relationships",
      "ledger er diagram",
      "ledger entity relationship diagram"
    ],
    "requiredKinds": [
      "table",
      "column"
    ],
    "requiredAcrossRepository": [
      "table",
      "column"
    ],
    "concern": "Data",
    "renderer": "er",
    "questionAnswered": "What ledger and persistence relationships are evidenced?",
    "description": "Sketch the double-entry writes and the INSERT IGNORE and batchId + \"_0\" behavior where the source supports them.",
    "example": "Create an ER-style ledger sketch for double-entry writes, INSERT IGNORE behavior, and batchId with the \"_0\" suffix. Ground each table or operation in repository evidence and note gaps.",
    "needs": []
  },
  "S5": {
    "id": "S5",
    "name": "test-guarantee matrix",
    "form": "TestConfidence",
    "version": 3,
    "compiler": "standard",
    "offline": "derived",
    "aliases": [
      "test-guarantee matrix",
      "test guarantee matrix",
      "test traceability matrix"
    ],
    "requiredKinds": [],
    "requiredAcrossRepository": [],
    "concern": "Quality",
    "renderer": "view-spec",
    "questionAnswered": "Which tests support the selected behaviors?",
    "description": "Map tests to behaviors and named invariants. Code reach and test names are signals; they do not alone prove an invariant.",
    "example": "Which tests support each reserve and ledger invariant? Separate tests that only reach code from tests whose names indicate an assertion, and show untested gaps.",
    "needs": [
      "tests"
    ]
  },
  "S6": {
    "id": "S6",
    "name": "Use case diagram",
    "form": "GeneratedChart",
    "version": 3,
    "compiler": "standard",
    "offline": "derived",
    "aliases": [
      "Use case diagram",
      "use case diagram",
      "usecase diagram"
    ],
    "requiredKinds": [],
    "requiredAcrossRepository": [],
    "concern": "Other views",
    "renderer": "view-spec",
    "questionAnswered": "How is this behavior decomposed?",
    "description": "Actors (callers, admins, external systems) and the use cases they trigger, grounded in the entry points and guard checks visible in the code. Missing actors and undeclared relationships are listed as gaps.",
    "example": "Draw a use case diagram for the bookkeeping component. Show each caller role and the operations (reserve, post, rollback, audit) they can invoke, based on entry-point and authorisation evidence in the code.",
    "needs": []
  },
  "S7": {
    "id": "S7",
    "name": "BPMN process diagram",
    "form": "GeneratedChart",
    "version": 3,
    "compiler": "specialized",
    "offline": "gap",
    "aliases": [
      "BPMN process diagram",
      "bpmn diagram",
      "business process diagram"
    ],
    "requiredKinds": [],
    "requiredAcrossRepository": [],
    "concern": "Behavior",
    "renderer": "view-spec",
    "questionAnswered": "What activities, decisions, and participants make up this process?",
    "description": "Business-process view: start/end events, tasks, XOR gateways and compensation boundaries, arranged as a BPMN-style flow grounded in indexed control-flow and error-handling evidence.",
    "example": "Draw a BPMN process diagram for the reserve → post / rollback flow. Show start and end events, decision gateways for provider response and DB sync, and the compensation boundary around cancelFast. Use only evidence from the indexed code.",
    "needs": []
  },
  "S8": {
    "id": "S8",
    "name": "Event storming / event modeling",
    "form": "GeneratedChart",
    "version": 3,
    "compiler": "specialized",
    "offline": "derived",
    "aliases": [
      "Event storming / event modeling",
      "event storming event modeling",
      "event storming board",
      "event model"
    ],
    "requiredKinds": [],
    "requiredAcrossRepository": [],
    "concern": "Other views",
    "renderer": "view-spec",
    "questionAnswered": "Which commands, events, and actors participate?",
    "description": "Commands, domain events and read models arranged on a timeline. Commands are derived from public entry points, events from emitted topics and state transitions, aggregates from the entities that own them.",
    "example": "Build an event storming board for the bookkeeping component. Place commands (Reserve, Post, Rollback), domain events (FundsReserved, TransactionPosted, LedgerEntryWritten, ReservationRolledBack) and the aggregates that own them on a timeline, grounded in indexed topics and state-transition evidence.",
    "needs": []
  },
  "S9": {
    "id": "S9",
    "name": "Entity-relationship diagram",
    "form": "GeneratedChart",
    "version": 4,
    "compiler": "specialized",
    "offline": "gap",
    "aliases": [
      "Entity-relationship diagram",
      "entity relationship er diagram",
      "er diagram",
      "entity relationship diagram",
      "entity relationship chart"
    ],
    "requiredKinds": [
      "table",
      "column"
    ],
    "requiredAcrossRepository": [
      "table",
      "column"
    ],
    "concern": "Data",
    "renderer": "er",
    "questionAnswered": "What entities, columns, and declared relationships exist?",
    "description": "All persisted tables, their key columns and foreign-key relationships as an ER sketch. Each table and relationship is traced to indexed schema or write-fact evidence; inferred relationships are shown dashed.",
    "example": "Draw an ER diagram for all persisted state in this repository: tables, primary keys, foreign keys and the relationships between them. Distinguish schema-evidenced relationships (solid) from inferred ones (dashed) and list gaps.",
    "needs": []
  },
  "S10": {
    "id": "S10",
    "name": "Data flow diagram",
    "form": "GeneratedChart",
    "version": 3,
    "compiler": "specialized",
    "offline": "derived",
    "aliases": [
      "Data flow diagram",
      "data flow diagram dfd",
      "dfd",
      "data flow chart"
    ],
    "requiredKinds": [],
    "requiredAcrossRepository": [],
    "concern": "Data",
    "renderer": "view-spec",
    "questionAnswered": "Where does data enter, move, and persist?",
    "description": "Data flows between processes, data stores and external entities across the whole reserve/post/rollback pipeline — showing what data moves, not which code calls which code. Complements V5 DataLineage which centres on one field.",
    "example": "Draw a level-1 data flow diagram for the bookkeeping component. Show external entities (caller, provider), processes (validate, reserve, persist, post ledger), data stores (Redis, transaction_state, ledger) and the data flows between them, grounded in indexed read/write facts.",
    "needs": []
  },
  "S11": {
    "id": "S11",
    "name": "Decision table",
    "form": "GeneratedChart",
    "version": 4,
    "compiler": "specialized",
    "offline": "gap",
    "aliases": [
      "Decision table",
      "decision matrix",
      "decision table"
    ],
    "requiredKinds": [
      "field"
    ],
    "requiredAcrossRepository": [
      "function",
      "method"
    ],
    "concern": "State and rules",
    "renderer": "table",
    "questionAnswered": "Which conditions determine each outcome?",
    "description": "Guard conditions (state exists, balance sufficient, DB sync result) mapped to outcomes (return existing, throw, compensate, persist). Each row is grounded in a branch condition visible in the indexed control-flow.",
    "example": "Build a decision table for the reserve operation. Rows are combinations of: state-already-exists, balance-sufficient, DB-sync-succeeded. Columns are the outcome actions. Cite the code branch that produces each outcome and mark any combination not evidenced in the code as a gap.",
    "needs": []
  },
  "S12": {
    "id": "S12",
    "name": "Saga / compensation graph",
    "form": "GeneratedChart",
    "version": 5,
    "compiler": "projected",
    "offline": "gap",
    "aliases": [
      "Saga / compensation graph",
      "saga graph",
      "compensation graph"
    ],
    "requiredKinds": [
      "function",
      "method"
    ],
    "requiredAcrossRepository": [],
    "concern": "Reliability",
    "renderer": "view-spec",
    "questionAnswered": "How do failures trigger compensation or recovery?",
    "description": "The forward steps (reserve → post) and their compensation counterparts (rollback, cancelFast) laid out as a saga graph. Each compensation edge is traced to the code that implements it; missing compensations are flagged as gaps.",
    "example": "Draw a saga compensation graph for the reserve → post → ledger flow. Show each forward step alongside its compensation action (rollback, cancelFast), the trigger condition (DB sync failure, provider failure), and cite the code evidence. Mark any forward step that has no visible compensation as a gap.",
    "needs": []
  },
  "S13": {
    "id": "S13",
    "name": "Outbox pattern topology",
    "form": "GeneratedChart",
    "version": 5,
    "compiler": "projected",
    "offline": "gap",
    "aliases": [
      "Outbox pattern topology",
      "outbox diagram",
      "outbox topology"
    ],
    "requiredKinds": [
      "function",
      "method"
    ],
    "requiredAcrossRepository": [],
    "concern": "Reliability",
    "renderer": "view-spec",
    "questionAnswered": "How do writers, stores, publishers, and consumers connect?",
    "description": "The transactional outbox: which service writes to it, which poller reads from it, and which downstream targets (provider, ledger) are driven by it — grounded in indexed write-to-outbox and publish-from-outbox evidence.",
    "example": "Draw the outbox pattern topology for the bookkeeping service. Show the service writing to the outbox table in the same transaction as state changes, the outbox poller, and the downstream targets it drives (provider callback, ledger writer). Cite the evidence for each step and list what could not be confirmed from the indexed code.",
    "needs": []
  },
  "S14": {
    "id": "S14",
    "name": "Idempotency matrix",
    "form": "GeneratedChart",
    "version": 4,
    "compiler": "projected",
    "offline": "gap",
    "aliases": [
      "Idempotency matrix",
      "idempotency matrix"
    ],
    "requiredKinds": [
      "function",
      "method"
    ],
    "requiredAcrossRepository": [],
    "concern": "Reliability",
    "renderer": "table",
    "questionAnswered": "Which mechanisms handle duplicate requests?",
    "description": "Each operation (reserve, post, rollback) crossed with its duplicate-call scenario, showing whether the result is idempotent and what mechanism enforces it (batchId lookup, INSERT IGNORE, Redis idempotency key). Missing guarantees are gaps.",
    "example": "Build an idempotency matrix for reserve, post and rollback. For each operation, show what happens on a duplicate call with the same batchId, which code mechanism enforces idempotency (state-exists check, INSERT IGNORE, Redis key), and cite the evidence. Mark any operation where idempotency is not evidenced as a gap.",
    "needs": []
  },
  "S15": {
    "id": "S15",
    "name": "DI wiring diagram",
    "form": "GeneratedChart",
    "version": 5,
    "compiler": "projected",
    "offline": "gap",
    "aliases": [
      "DI wiring diagram",
      "di wiring diagram",
      "dependency injection diagram",
      "di diagram",
      "wiring diagram"
    ],
    "requiredKinds": [
      "class",
      "interface"
    ],
    "requiredAcrossRepository": [],
    "concern": "Structure",
    "renderer": "view-spec",
    "questionAnswered": "How are dependencies injected and resolved?",
    "description": "Which classes are injected into which, how the dependency graph is wired by the container, and where circular or missing bindings would appear. Grounded in constructor-injection and field-injection evidence from the indexed code.",
    "example": "Draw the dependency-injection wiring diagram for the bookkeeping component. Show which implementations are injected into which classes (BookkeepingEngineImpl → ReserveService → BalanceService, TransactionStateService, LedgerWriterServiceImpl), the injection mechanism (constructor vs field), and flag any dependency that could not be confirmed from the indexed code.",
    "needs": []
  },
  "S16": {
    "id": "S16",
    "name": "UML class diagram",
    "form": "GeneratedChart",
    "version": 3,
    "compiler": "specialized",
    "offline": "gap",
    "aliases": [
      "UML class diagram",
      "class diagram",
      "uml class diagram"
    ],
    "requiredKinds": [
      "class",
      "interface",
      "enum",
      "field",
      "method"
    ],
    "requiredAcrossRepository": [],
    "concern": "Structure",
    "renderer": "view-spec",
    "questionAnswered": "What types, members, and type relationships exist?",
    "description": "Classes, interfaces, enums and their attributes and operations, with inheritance (hollow triangle), realization, association, aggregation/composition (diamond at the owner end) and dependency relations. Relations not declared in source are drawn dashed and named as inferred.",
    "example": "Draw a UML class diagram for the bookkeeping domain: classes with their evidenced attributes and operations, inheritance and realization between them, and the associations the code declares. Mark anything not declared in source as inferred and list gaps.",
    "needs": []
  },
  "S17": {
    "id": "S17",
    "name": "UML package diagram",
    "form": "GeneratedChart",
    "version": 5,
    "compiler": "projected",
    "offline": "gap",
    "aliases": [
      "UML package diagram",
      "package diagram",
      "uml package diagram"
    ],
    "requiredKinds": [
      "class",
      "interface",
      "module",
      "package",
      "function",
      "method"
    ],
    "requiredAcrossRepository": [
      "class",
      "interface",
      "module",
      "package",
      "function",
      "method"
    ],
    "concern": "Structure",
    "renderer": "view-spec",
    "questionAnswered": "How are packages connected?",
    "description": "Packages/namespaces with their evidenced members and the dependencies between them, drawn dashed. Members come from the indexed declarations only.",
    "example": "Draw a UML package diagram for this repository: the main packages, the classes or modules each contains, and which packages depend on which. Cite the declarations that evidence each dependency and list gaps.",
    "needs": []
  },
  "S18": {
    "id": "S18",
    "name": "UML communication diagram",
    "form": "GeneratedChart",
    "version": 5,
    "compiler": "projected",
    "offline": "gap",
    "aliases": [
      "UML communication diagram",
      "communication diagram",
      "uml communication diagram"
    ],
    "requiredKinds": [
      "function",
      "method"
    ],
    "requiredAcrossRepository": [],
    "concern": "Behavior",
    "renderer": "view-spec",
    "questionAnswered": "Which participants communicate with each other?",
    "description": "Participants linked by numbered messages: each message carries its sequence number, direction and kind (sync, async, return). The numbering gives the interaction order.",
    "example": "Draw a UML communication diagram for the reserve flow: the caller, engine, balance, state and ledger participants, with numbered messages (1: reserve, 2: tryReserveFast, …) grounded in the indexed call relationships.",
    "needs": []
  },
  "S19": {
    "id": "S19",
    "name": "UML interaction overview",
    "form": "GeneratedChart",
    "version": 5,
    "compiler": "projected",
    "offline": "gap",
    "aliases": [
      "UML interaction overview",
      "interaction overview diagram",
      "uml interaction overview"
    ],
    "requiredKinds": [
      "function",
      "method"
    ],
    "requiredAcrossRepository": [],
    "concern": "Behavior",
    "renderer": "view-spec",
    "questionAnswered": "How do interactions compose into a larger flow?",
    "description": "The control-flow between interactions: initial and final markers, interaction frames that name the nested interaction they refer to, and decision points with guards on the outgoing flows.",
    "example": "Draw an interaction overview for the bookkeeping lifecycle: one interaction frame per operation (reserve, post, rollback), connected through decision points with the guards the code evidences.",
    "needs": []
  },
  "S20": {
    "id": "S20",
    "name": "CRC cards",
    "form": "GeneratedChart",
    "version": 6,
    "compiler": "projected",
    "offline": "gap",
    "aliases": [
      "CRC cards",
      "crc cards",
      "class responsibility collaborator cards"
    ],
    "requiredKinds": [],
    "requiredAcrossRepository": [],
    "concern": "Structure",
    "renderer": "table",
    "questionAnswered": "Which responsibilities and collaborators belong to each type?",
    "description": "One card per class: its evidenced responsibilities and the classes it collaborates with, rendered as a source-linked table with responsibility and collaborator cells. Entries the source does not support are listed as gaps, not invented.",
    "example": "Build CRC cards for ReserveService, BalanceService, TransactionStateService and LedgerWriterServiceImpl. List each class's responsibilities and collaborators, citing the code that evidences each entry.",
    "needs": []
  },
  "S21": {
    "id": "S21",
    "name": "Call graph",
    "form": "GeneratedChart",
    "version": 5,
    "compiler": "projected",
    "offline": "derived",
    "aliases": [
      "Call graph",
      "call graph"
    ],
    "requiredKinds": [
      "function",
      "method"
    ],
    "requiredAcrossRepository": [],
    "concern": "Behavior",
    "renderer": "view-spec",
    "questionAnswered": "Which functions call which other functions?",
    "description": "Which functions call which, from statically resolved call relationships. Every edge is static source evidence; no runtime frequency or ordering beyond source order is implied.",
    "example": "Draw the call graph rooted at reserve: each function it reaches through resolved calls, with the call-site evidence for every edge. Flag calls the indexer could not resolve.",
    "needs": []
  },
  "S22": {
    "id": "S22",
    "name": "Layered architecture",
    "form": "GeneratedChart",
    "version": 5,
    "compiler": "projected",
    "offline": "gap",
    "aliases": [
      "Layered architecture",
      "layered architecture",
      "layer diagram",
      "layered architecture diagram"
    ],
    "requiredKinds": [],
    "requiredAcrossRepository": [],
    "concern": "Structure",
    "renderer": "view-spec",
    "questionAnswered": "What layers and dependencies are evidenced?",
    "description": "Components grouped into named, ordered layers (API, service, domain, infrastructure…), with uses/calls and asynchronous dependencies between them. Layers only appear when the code evidences them.",
    "example": "Draw the layered architecture of this service: an API layer, an application-service layer, a domain layer and an infrastructure layer, with the components the code places in each and the dependencies between layers.",
    "needs": []
  },
  "S23": {
    "id": "S23",
    "name": "Dependency / module graph",
    "form": "GeneratedChart",
    "version": 5,
    "compiler": "projected",
    "offline": "gap",
    "aliases": [
      "Dependency / module graph",
      "dependency module graph",
      "module graph",
      "dependency graph",
      "module dependency diagram"
    ],
    "requiredKinds": [
      "module",
      "package",
      "crate",
      "workspace",
      "class",
      "interface",
      "function",
      "method"
    ],
    "requiredAcrossRepository": [
      "module",
      "package",
      "crate",
      "workspace",
      "class",
      "interface",
      "function",
      "method"
    ],
    "concern": "Structure",
    "renderer": "view-spec",
    "questionAnswered": "How are modules and components connected?",
    "description": "Modules, packages and crates with the dependencies between them, labelled by kind (compile-time, runtime, test-only). Cycles and unsupported dependencies are shown as what they are.",
    "example": "Draw the module dependency graph for this repository: each module/package, whether dependencies are compile-time, runtime or test-only, and any circular dependency the resolved graph contains.",
    "needs": []
  },
  "S24": {
    "id": "S24",
    "name": "State transition table",
    "form": "GeneratedChart",
    "version": 5,
    "compiler": "projected",
    "offline": "gap",
    "aliases": [
      "State transition table",
      "state transition table",
      "transition table"
    ],
    "requiredKinds": [],
    "requiredAcrossRepository": [],
    "concern": "State and rules",
    "renderer": "table",
    "questionAnswered": "Which triggers move between states?",
    "description": "A real table: current state × event → next state, with guards and forbidden transitions as negative facts. Combinations the source does not cover stay visibly unknown.",
    "example": "Build the state transition table for the batchId lifecycle: rows for NoState, Reserved, Posted and RolledBack; columns for reserve, post and rollback; each cell names the next state and its guard, and forbidden transitions (rollback after post) are marked as forbidden.",
    "needs": []
  },
  "S25": {
    "id": "S25",
    "name": "FMEA / compensation matrix",
    "form": "GeneratedChart",
    "version": 5,
    "compiler": "projected",
    "offline": "gap",
    "aliases": [
      "FMEA / compensation matrix",
      "fmea compensation matrix",
      "fmea matrix",
      "failure mode analysis"
    ],
    "requiredKinds": [
      "function",
      "method"
    ],
    "requiredAcrossRepository": [
      "function",
      "method"
    ],
    "concern": "Reliability",
    "renderer": "table",
    "questionAnswered": "What failure modes and mitigations are evidenced?",
    "description": "Failure mode × impact × compensation as a table, each cell backed by source or test evidence. A failure with no evidenced compensation is listed as a gap, never assumed recoverable.",
    "example": "Build an FMEA matrix for the reserve fast path: Redis reserve failure, DB sync failure, provider failure, duplicate post. For each, the evidenced impact and the compensation in the code (cancelFast, rollback, INSERT IGNORE), and mark any failure without a compensation.",
    "needs": []
  },
  "S26": {
    "id": "S26",
    "name": "Metrics / telemetry map",
    "form": "GeneratedChart",
    "version": 6,
    "compiler": "projected",
    "offline": "gap",
    "aliases": [
      "Metrics / telemetry map",
      "metrics telemetry map",
      "metrics map",
      "telemetry map"
    ],
    "requiredKinds": [],
    "requiredAcrossRepository": [
      "function",
      "method"
    ],
    "concern": "Quality",
    "renderer": "table",
    "questionAnswered": "Which measurements and monitored components are evidenced?",
    "description": "Metric names as declared in code, with their evidenced meaning and emitters. Declared names only — this chart never reports live values.",
    "example": "List the metrics this component declares (reservation.fast.success, ledger.insert.ignored, …), what each measures based on the code that emits it, and which functions emit them. Do not invent live values.",
    "needs": []
  },
  "S27": {
    "id": "S27",
    "name": "System context",
    "form": "GeneratedChart",
    "version": 5,
    "compiler": "projected",
    "offline": "gap",
    "aliases": [
      "C4 context diagram",
      "c4 context diagram",
      "context diagram"
    ],
    "requiredKinds": [
      "class",
      "function"
    ],
    "requiredAcrossRepository": [
      "class",
      "function"
    ],
    "concern": "Structure",
    "renderer": "view-spec",
    "questionAnswered": "What actors, systems, and external boundaries are evidenced?",
    "description": "The widest view: people, the subject software system and external systems, with labelled relationships (operation, protocol or data purpose). Containers and components stay out of scope at context level (use S1 for those).",
    "example": "Draw a system context diagram for the bookkeeping system: the caller and admin roles, the bookkeeping system itself, and Redis, MySQL and the provider as external systems, with the evidenced operations on each relationship.",
    "needs": []
  },
  "S28": {
    "id": "S28",
    "name": "UML sequence diagram",
    "form": "GeneratedChart",
    "version": 6,
    "compiler": "projected",
    "offline": "gap",
    "aliases": [
      "UML sequence diagram",
      "uml sequence diagram",
      "sequence diagram"
    ],
    "requiredKinds": [
      "function",
      "method"
    ],
    "requiredAcrossRepository": [],
    "concern": "Behavior",
    "renderer": "sequence",
    "questionAnswered": "What interaction order is supported by the available evidence?",
    "description": "Lifelines with ordered messages (sync, async, return, self) and alt/opt/loop/exception/parallel fragment regions, ordered by static control-flow — not observed runtime timing. Rendered as lifelines and message rows. Message ordering and fragment semantics are inferred from the supplied static plan, not proven by the presence of source evidence.",
    "example": "Draw the reserve interaction as a UML sequence diagram: caller, engine, Redis and MySQL lifelines; numbered messages in evidenced order; an alt fragment for insufficient balance and an exception fragment for the DB-sync compensation.",
    "needs": []
  },
  "S29": {
    "id": "S29",
    "name": "Control flow graph",
    "form": "GeneratedChart",
    "version": 3,
    "compiler": "missing",
    "offline": "gap",
    "aliases": [
      "Control flow graph",
      "control flow graph",
      "cfg",
      "control flow diagram"
    ],
    "requiredKinds": [
      "function",
      "method"
    ],
    "requiredAcrossRepository": [],
    "concern": "Behavior",
    "renderer": "view-spec",
    "questionAnswered": "What branches and control-flow paths are evidenced?",
    "description": "Evidence-grounded Control flow graph",
    "example": "Show Control flow graph",
    "needs": []
  },
  "generic": {
    "id": "generic",
    "name": "Generated chart",
    "form": "GeneratedChart",
    "version": 3,
    "compiler": "standard",
    "offline": "derived",
    "aliases": [
      "Generated chart"
    ],
    "requiredKinds": [],
    "requiredAcrossRepository": [],
    "concern": "Other views",
    "renderer": "view-spec",
    "questionAnswered": "What relationships in the indexed evidence answer this question?",
    "description": "Evidence-grounded Generated chart",
    "example": "Show Generated chart",
    "needs": []
  }
} as const satisfies { [K in ChartId]: ChartDescriptor<K> };
