// Generated by scripts/generate-plugins.ts. Do not edit.
import type { WorkflowStep } from "@cie/schema";
import type { PlanningContext } from "../../answer-planning.ts";
import s0 from "./interpret.step.ts";
import s1 from "./probe-evidence.step.ts";
import s2 from "./rank-views.step.ts";
export const RESPONSE_STEPS = [s0, s1, s2] satisfies WorkflowStep<PlanningContext>[];
