// Labelled routing questions shared by the router tests and the model evaluation (scripts/eval-tiny-models.ts).
export type Case = [question: string, form: string, kind?: string];

export const DEV: Case[] = [
  ["Show me how authentication works", "SemanticMap"],
  ["explain the payment module", "SemanticMap"],
  ["what does the ledger do", "SemanticMap"],
  ["Show me everything that could cause a payment to fail", "CausalGraph", "failure"],
  ["what can make a transfer break", "CausalGraph", "failure"],
  ["why would createPayment throw an error", "CausalGraph", "failure"],
  ["Why could this balance become incorrect?", "CausalGraph", "invariant"],
  ["how can the ledger drift out of sync", "CausalGraph", "invariant"],
  ["Walk me through createPayment step by step", "TransactionJourney"],
  ["what happens when a user refunds an order", "TransactionJourney"],
  ["follow a request end to end through checkout", "TransactionJourney"],
  ["Who reads and writes balance?", "DataLineage"],
  ["where is the account status updated", "DataLineage"],
  ["who modifies the invoice table", "DataLineage"],
  ["What changed since the last index?", "SemanticDiff"],
  ["compare this version with the last release", "SemanticDiff"],
  ["what is different between the two revisions", "SemanticDiff"],
  ["Why is adjustBalance not transactional?", "Archaeology"],
  ["how did the retry logic end up like this", "Archaeology"],
  ["tell me the history of the fee calculation", "Archaeology"],
  ["Who can reach adjustBalance and what stops them?", "TrustBoundary"],
  ["what would an attacker be able to reach from the public api", "TrustBoundary"],
  ["which endpoints are exposed without authorization", "TrustBoundary"],
  ["What has been going wrong in the last 7 days?", "RuntimeOverlay"],
  ["show reported incidents on the code", "RuntimeOverlay"],
  ["what is breaking in production", "RuntimeOverlay"],
  ["Where can balance race?", "RaceWindow"],
  ["can two requests hit the ledger at the same time", "RaceWindow"],
  ["is there a concurrency problem with transfers", "RaceWindow"],
  ["What if we remove the ledger module?", "Counterfactual"],
  ["what would break if we delete the cache", "Counterfactual"],
  ["is it safe to retire the legacy exporter", "Counterfactual"],
  ["How well tested are our operations?", "TestConfidence"],
  ["which behaviours have no test", "TestConfidence"],
  ["how much of the payment code is covered by tests", "TestConfidence"],
  ["Who owns what and where is the bus factor 1?", "Ownership"],
  ["who is the expert on billing", "Ownership"],
  ["who should review changes to the scheduler", "Ownership"],
  ["Show the implicit concepts in this code", "ConceptAtlas"],
  ["what unwritten business rules does this code follow", "ConceptAtlas"],
  ["list the undocumented assumptions", "ConceptAtlas"],
  ["Which policies are enforced and where do they have gaps?", "PolicyMap"],
  ["which routes get around the audit rule", "PolicyMap"],
  ["are our compliance rules actually enforced", "PolicyMap"],
  ["Where is it risky to change things?", "ChangeRisk"],
  ["which files are the most fragile", "ChangeRisk"],
  ["where is the technical debt worst", "ChangeRisk"],
  // migrated from the first held-out set after its misses informed the vocabulary
["how is the notification system put together", "SemanticMap"],
  ["describe the structure of the billing code", "SemanticMap"],
  ["what makes a checkout fail", "CausalGraph", "failure"],
  ["ways the refund job can crash", "CausalGraph", "failure"],
  ["how could the stock count end up wrong", "CausalGraph", "invariant"],
  ["can the wallet balance go negative", "CausalGraph", "invariant"],
  ["trace what occurs when an invoice is voided", "TransactionJourney"],
  ["take me through the signup flow", "TransactionJourney"],
  ["which functions write to the orders table", "DataLineage"],
  ["who touches the session state", "DataLineage"],
  ["summarise what is new since the previous revision", "SemanticDiff"],
  ["show the diff in behaviour between releases", "SemanticDiff"],
  ["why was the cache layer written this way", "Archaeology"],
  ["where did this workaround come from", "Archaeology"],
  ["can an unauthenticated caller get to the admin functions", "TrustBoundary"],
  ["what protects the payout path", "TrustBoundary"],
  ["which errors were reported this week", "RuntimeOverlay"],
  ["map the incidents onto the modules", "RuntimeOverlay"],
  ["could two jobs process the same payment simultaneously", "RaceWindow"],
  ["where are there thread safety problems", "RaceWindow"],
  ["what depends on the email service if we drop it", "Counterfactual"],
  ["what breaks without the rate limiter", "Counterfactual"],
  ["which parts have weak test coverage", "TestConfidence"],
  ["are the refund paths tested", "TestConfidence"],
  ["who maintains the search module", "Ownership"],
  ["where does only one person know the code", "Ownership"],
  ["what domain concepts are hidden in this repo", "ConceptAtlas"],
  ["show me conventions nobody wrote down", "ConceptAtlas"],
  ["which rules do we bypass", "PolicyMap"],
  ["where is the validation rule not enforced", "PolicyMap"],
  ["which module is riskiest to touch", "ChangeRisk"],
  ["where would a refactor hurt most", "ChangeRisk"],
];

export const HELD_OUT: Case[] = [
  ["how are the background workers organised", "SemanticMap"],
  ["what makes a subscription renewal fail", "CausalGraph", "failure"],
  ["what could make the webhook handler blow up", "CausalGraph", "failure"],
  ["how might the inventory count get out of step", "CausalGraph", "invariant"],
  ["can the credit total ever be wrong", "CausalGraph", "invariant"],
  ["show what happens, in order, when someone cancels a plan", "TransactionJourney"],
  ["go through the onboarding sequence", "TransactionJourney"],
  ["what code updates the customer record", "DataLineage"],
  ["which functions read the feature flags", "DataLineage"],
  ["what is new compared with the previous index", "SemanticDiff"],
  ["how has behaviour changed since the last revision", "SemanticDiff"],
  ["how come the scheduler works like this", "Archaeology"],
  ["what is the story behind the retry wrapper", "Archaeology"],
  ["who is able to call the delete endpoint and what checks them", "TrustBoundary"],
  ["where is the privilege boundary", "TrustBoundary"],
  ["which exceptions came in recently", "RuntimeOverlay"],
  ["overlay the failing tests on the modules", "RuntimeOverlay"],
  ["could two workers pick up the same job", "RaceWindow"],
  ["is the counter update atomic", "RaceWindow"],
  ["what would stop working if the queue went away", "Counterfactual"],
  ["what is the blast radius of removing the auth middleware", "Counterfactual"],
  ["which operations lack a safety net of tests", "TestConfidence"],
  ["is the export path covered", "TestConfidence"],
  ["who knows the payments code best", "Ownership"],
  ["which files have a single contributor", "Ownership"],
  ["what implicit rules does the pricing code encode", "ConceptAtlas"],
  ["surface the domain vocabulary buried in the code", "ConceptAtlas"],
  ["which guard rails are only held by convention", "PolicyMap"],
  ["where do we skip the approval check", "PolicyMap"],
  ["what is the most brittle part of the codebase", "ChangeRisk"],
  ["where does churn and coupling pile up", "ChangeRisk"],
];

// A second held-out set, written after the nearest-neighbour layer existed and never used to tune anything. Run once per change.
export const HELD_OUT_V2: Case[] = [
  ["what design does this application use", "SemanticMap"],
  ["can you give me a high level picture of how the pieces connect", "SemanticMap"],
  ["what causes the nightly export to abort", "CausalGraph", "failure"],
  ["in which situations can the webhook handler return an error", "CausalGraph", "failure"],
  ["how might customer credits disagree with the invoices", "CausalGraph", "invariant"],
  ["what could leave the shipment count off", "CausalGraph", "invariant"],
  ["what does a request go through when someone checks out", "TransactionJourney"],
  ["narrate the onboarding of a new tenant", "TransactionJourney"],
  ["which methods change the order total", "DataLineage"],
  ["what looks at the retry counter", "DataLineage"],
  ["how is this release different from the one before", "SemanticDiff"],
  ["what behaviour shifted in the recent merge", "SemanticDiff"],
  ["what drove the decision to use a custom scheduler", "Archaeology"],
  ["how did the permission model get like this", "Archaeology"],
  ["what protects the internal admin api from outsiders", "TrustBoundary"],
  ["can someone without a login read other users data", "TrustBoundary"],
  ["which services are crashing according to our error reports", "RuntimeOverlay"],
  ["where are the production incidents concentrated", "RuntimeOverlay"],
  ["might two processes both claim the same invoice", "RaceWindow"],
  ["is it safe to call the allocator from several threads", "RaceWindow"],
  ["what are the consequences of dropping the audit module", "Counterfactual"],
  ["what would we lose if the search index went offline", "Counterfactual"],
  ["which behaviours have no automated checks", "TestConfidence"],
  ["are there tests for the permission logic", "TestConfidence"],
  ["who are the people behind the reporting code", "Ownership"],
  ["which modules are known by only one developer", "Ownership"],
  ["what domain terms are implied by the discount logic", "ConceptAtlas"],
  ["what unspoken rules apply to tax calculation", "ConceptAtlas"],
  ["which business rules can be sidestepped", "PolicyMap"],
  ["is the data retention requirement really applied everywhere", "PolicyMap"],
  ["where would a change be most likely to break something", "ChangeRisk"],
  ["which area is the riskiest to modify", "ChangeRisk"],
  ["what architecture does this project follow", "SemanticMap"],
  ["how is the codebase laid out", "SemanticMap"],
];

// Third set, written last and run once with no tuning afterwards: this is the number to quote.
export const HELD_OUT_V3: Case[] = [
  ["what is the overall design of this service", "SemanticMap"],
  ["what makes the report generator throw", "CausalGraph", "failure"],
  ["how could the wallet amount become wrong", "CausalGraph", "invariant"],
  ["show the order of operations when a ticket is closed", "TransactionJourney"],
  ["what code changes the subscription state", "DataLineage"],
  ["what differs in the new build", "SemanticDiff"],
  ["why does the legacy parser exist", "Archaeology"],
  ["which entry points lack authentication", "TrustBoundary"],
  ["what are the live exceptions in the api layer", "RuntimeOverlay"],
  ["can the cache refresh run simultaneously with a write", "RaceWindow"],
  ["what breaks if the payment gateway client is removed", "Counterfactual"],
  ["which modules lack test coverage", "TestConfidence"],
  ["who is the main author of the gateway code", "Ownership"],
  ["what hidden domain rules does the invoice code follow", "ConceptAtlas"],
  ["where is the data policy not enforced", "PolicyMap"],
  ["which files are risky to refactor", "ChangeRisk"],
  ["how is the repository structured", "SemanticMap"],
  ["what are the failure modes of the batch importer", "CausalGraph", "failure"],
  ["walk through what happens when an account is deleted", "TransactionJourney"],
  ["which code reads the user role", "DataLineage"],
];
