import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join } from "node:path";
import ts from "typescript";
import { ChartDescriptorSchema } from "../packages/schema/src/plugins/chart-module.ts";
const root = fileURLToPath(new URL("../", import.meta.url));
export function literal(node: ts.Expression): unknown {
  if (ts.isAsExpression(node) || ts.isSatisfiesExpression(node) || ts.isParenthesizedExpression(node)) return literal(node.expression);
  if (ts.isStringLiteral(node)) return node.text;
  if (ts.isNumericLiteral(node)) return Number(node.text);
  if (node.kind === ts.SyntaxKind.TrueKeyword) return true;
  if (node.kind === ts.SyntaxKind.FalseKeyword) return false;
  if (ts.isArrayLiteralExpression(node)) return node.elements.map((e) => literal(e as ts.Expression));
  if (ts.isObjectLiteralExpression(node)) return Object.fromEntries(node.properties.map((p) => {
    if (!ts.isPropertyAssignment(p) || !p.name || !ts.isIdentifier(p.name) && !ts.isStringLiteral(p.name)) throw new Error("Plugin metadata must use literal properties");
    return [p.name.text, literal(p.initializer)];
  }));
  throw new Error("Plugin metadata must be static literals; expressions and spreads are not supported");
}
function declared(file: string, name: string) {
  const source = ts.createSourceFile(file, readFileSync(file, "utf8"), ts.ScriptTarget.Latest, true);
  for (const statement of source.statements) if (ts.isVariableStatement(statement) && statement.modifiers?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword)) {
    for (const d of statement.declarationList.declarations) if (ts.isIdentifier(d.name) && d.name.text === name && d.initializer) return literal(d.initializer);
  }
  throw new Error(`${file}: export a literal ${name}`);
}
export function unique<T extends { id: string }>(items: T[]): T[] {
  const seen = new Set<string>();
  for (const item of items) { if (seen.has(item.id)) throw new Error(`Duplicate plugin id: ${item.id}`); seen.add(item.id); }
  return items;
}
export function validatePairings(charts: { id: string; renderer: string }[], renderers: { id: string }[]) {
  unique(charts); unique(renderers);
  for (const chart of charts) if (!renderers.some((r) => r.id === chart.renderer)) throw new Error(`${chart.id}: missing renderer ${chart.renderer}`);
}
export function generate(check = false) {
  const dir = join(root, "packages/core/src/plugins/charts");
  const charts = unique(readdirSync(dir).filter((f) => f.endsWith(".chart.ts")).sort().map((file) => ({ file, ...ChartDescriptorSchema.parse(declared(join(dir, file), "descriptor")) })));
  const rendererDir = join(root, "apps/web/src/plugins/renderers");
  const renderers = unique(readdirSync(rendererDir).filter((f) => (f.endsWith(".renderer.ts") || f.endsWith(".renderer.tsx"))).sort().map((file) => ({ file, id: String(declared(join(rendererDir, file), "id")) })));
  validatePairings(charts, renderers);
  charts.sort((a, b) => (Number(a.id.slice(1)) || 1e9) - (Number(b.id.slice(1)) || 1e9));
  const stepDir = join(root, "packages/core/src/plugins/steps");
  const steps = unique(readdirSync(stepDir).filter(f => f.endsWith(".step.ts")).sort().map(file => ({ file, id: String(declared(join(stepDir, file), "id")) })));
  const banner = "// Generated by scripts/generate-plugins.ts. Do not edit.\n";
  const outputs = new Map<string, string>([
    ["packages/core/src/plugins/steps/registry.generated.ts", banner+'import type { WorkflowStep } from "@cie/schema";\nimport type { PlanningContext } from "../../answer-planning.ts";\n'+steps.map((s,i)=>`import s${i} from "./${s.file}";`).join("\n")+'\nexport const RESPONSE_STEPS = ['+steps.map((s,i)=>`s${i}`).join(", ")+'] satisfies WorkflowStep<PlanningContext>[];\n'],
    ["packages/schema/src/plugins/catalog.generated.ts", banner+'import type { ChartId, ChartDescriptor } from "../index.ts";\nexport const CHART_DESCRIPTORS = '+JSON.stringify(Object.fromEntries(charts.map(({ file, ...d }) => [d.id, d])), null, 2)+' as const satisfies { [K in ChartId]: ChartDescriptor<K> };\n'],
    ["packages/core/src/plugins/charts/registry.generated.ts", banner+'import type { ChartId, ChartModule } from "@cie/schema";\n'+charts.map((c,i)=>`import p${i} from "./${c.file}";`).join("\n")+'\nexport const CHART_MODULES = {\n'+charts.map((c,i)=>`  ${JSON.stringify(c.id)}: p${i},`).join("\n")+'\n} satisfies { [K in ChartId]: ChartModule<K> };\n'],
    ["apps/web/src/plugins/renderers/registry.generated.ts", banner+'import type { RendererId, RendererModule } from "@cie/schema";\nimport type { Rendered } from "../../graph.ts";\n'+renderers.map((r,i)=>`import r${i} from "./${r.file}";`).join("\n")+'\nexport const RENDERERS = {\n'+renderers.map((r,i)=>`  ${JSON.stringify(r.id)}: r${i},`).join("\n")+'\n} satisfies { [K in RendererId]: RendererModule<K, Rendered> };\n'],
  ]);
  for (const [file, expected] of outputs) {
    if (check) { if (readFileSync(join(root, file), "utf8") !== expected) throw new Error(`Stale generated registry: ${file}. Run npm run plugins:generate`); }
    else writeFileSync(join(root, file), expected);
  }
  return { charts: charts.length, renderers: renderers.length };
}
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) console.log(generate(process.argv.includes("--check")));
