// Generated by scripts/generate-plugins.ts. Do not edit.
import type { RendererId, RendererModule } from "@cie/schema";
import type { Rendered } from "../../graph.ts";
import r0 from "./er.renderer.ts";
import r1 from "./sequence.renderer.ts";
import r2 from "./state.renderer.ts";
import r3 from "./view-spec.renderer.ts";
export const RENDERERS = {
  "er": r0,
  "sequence": r1,
  "state": r2,
  "view-spec": r3,
} satisfies { [K in RendererId]: RendererModule<K, Rendered> };
